### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "username": "MegHunter01",
  "email": "meghunter01@example.com",
  "image_url": "https://i.etsystatic.com/5592462/r/il/5ac3c7/575537031/il_794xN.575537031_11h1.jpg",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "meghunter01@example.com",
  "password": "password"
}

### Fossil Areas Index
GET http://localhost:3000/fossil_areas.json

### Fossil Areas Create
POST http://localhost:3000/fossil_areas.json
Content-Type: application/json

{
  "state_name": "TEST",
  "area_name": "TEST",
  "geologic_formation": "TEST",
  "hyperlink": "TEST",
  "address": "TEST",
  "era": "TEST",
  "description": "TEST"
}